name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Cypress tests with official action
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm start
          wait-on: 'http://localhost:3000' # Optional, jika kamu perlu start app dulu
          command: npm run cypress:run # Atau npx cypress run
          browser: chrome # Optional, bisa chrome, firefox, electron

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
